llm:
  model: gemini-2.0-flash
  embedding: models/text-embedding-004
  maximum_information_acquisition_rate: 0.15 # (Values ​​from 0 to 1)
  maximum_retriever_attempts: 2

fastapi:
  api_limit: 1 # per minutes
  api_limit_cooldown: 60 # in seconds
  session_timeout: 3 # per minutes
  session_timeout_check_period: 60 # in seconds